version: "3.9"

services:
  app:
    build: 
      context: .
    container_name: instagram.app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: instagram.db
    environment:
      POSTGRES_USER: ${DB_USER:-instagram}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-instagram}
      POSTGRES_DB: ${DB_NAME:-instagram}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: instagram.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80
    
volumes:
  postgres_data:


networks:
  default:
    driver: bridge